# Generated by Django 6.0.5 on 2026-06-09 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_a_to_b', models.FloatField()),
                ('score_b_to_a', models.FloatField()),
                ('mutual_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('notification_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RevealRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slotmate_app.match')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reveals', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_reveals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlotRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_course_code', models.CharField(max_length=20)),
                ('current_section', models.CharField(max_length=10)),
                ('current_faculty', models.CharField(max_length=10)),
                ('current_time', models.CharField(max_length=50)),
                ('current_days', models.CharField(max_length=100)),
                ('preferred_course_code', models.CharField(max_length=20)),
                ('preferred_section', models.CharField(blank=True, max_length=10, null=True)),
                ('preferred_faculty', models.CharField(blank=True, max_length=10, null=True)),
                ('preferred_time', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_days', models.CharField(blank=True, max_length=100, null=True)),
                ('any_day', models.BooleanField(default=False)),
                ('any_time', models.BooleanField(default=False)),
                ('any_section', models.BooleanField(default=False)),
                ('any_faculty', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='request_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_a', to='slotmate_app.slotrequest'),
        ),
        migrations.AddField(
            model_name='match',
            name='request_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_b', to='slotmate_app.slotrequest'),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('department', models.TextField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('request_a', 'request_b')},
        ),
    ]
