# Generated by Django 6.0.5 on 2026-05-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotmate_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_id',
        ),
    ]
