# Generated by Django 6.0.5 on 2026-05-22 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotmate_app', '0002_remove_studentprofile_student_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_course_code', models.CharField(max_length=20)),
                ('current_section', models.CharField(max_length=10)),
                ('current_faculty', models.CharField(max_length=10)),
                ('current_time', models.CharField(max_length=50)),
                ('current_days', models.CharField(max_length=100)),
                ('preferred_course_code', models.CharField(max_length=20)),
                ('preferred_section', models.CharField(max_length=10)),
                ('preferred_faculty', models.CharField(max_length=10)),
                ('preferred_time', models.CharField(max_length=50)),
                ('preferred_days', models.CharField(max_length=100)),
                ('any_day', models.BooleanField(default=False)),
                ('any_time', models.BooleanField(default=False)),
                ('any_section', models.BooleanField(default=False)),
                ('any_faculty', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
