# Generated by Django 6.0.5 on 2026-05-28 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotmate_app', '0003_slotrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_a_to_b', models.FloatField()),
                ('score_b_to_a', models.FloatField()),
                ('mutual_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_a', to='slotmate_app.slotrequest')),
                ('request_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_b', to='slotmate_app.slotrequest')),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_a', 'user_b')},
            },
        ),
    ]
