# Generated by Django 6.0.5 on 2026-06-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotmate_app', '0004_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotrequest',
            name='preferred_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slotrequest',
            name='preferred_faculty',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='slotrequest',
            name='preferred_section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='slotrequest',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
