# Generated by Django 6.0.5 on 2026-06-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotmate_app', '0006_revealrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
