# Generated by Django 6.0.5 on 2026-06-04 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotmate_app', '0005_alter_slotrequest_preferred_days_and_more'),
        ('slotmate_app', '0007_notification_notification_type_and_more'),
    ]

    operations = [
    ]
