# Generated by Django 6.0.5 on 2026-06-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotmate_app', '0008_merge_20260604_1052'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('request_a', 'request_b')},
        ),
    ]
